#include "Lumen/Renderer/Renderer.h"

#include "Lumen/Assets/AssetManager.h"
#include "Lumen/Core/Log.h"
#include "Lumen/Renderer/Mesh.h"
#include "Lumen/Renderer/MipChain.h"
#include "Lumen/Scene/Scene.h"

#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>

#include <algorithm>
#include <array>
#include <cstddef>
#include <map>
#include <unordered_map>
#include <unordered_set>

// Generated by cmake/Shaders.cmake from Lumen/shaders/.
extern const unsigned char g_Shader_mesh_vert[];
extern const size_t g_Shader_mesh_vert_size;
extern const unsigned char g_Shader_pbr_frag[];
extern const size_t g_Shader_pbr_frag_size;
extern const unsigned char g_Shader_fullscreen_vert[];
extern const size_t g_Shader_fullscreen_vert_size;
extern const unsigned char g_Shader_tonemap_frag[];
extern const size_t g_Shader_tonemap_frag_size;

namespace Lumen {

	namespace {

		// std140 layout, matches the Frame block in the shaders.
		struct FrameConstants
		{
			glm::mat4 View;
			glm::mat4 Proj;
			glm::vec4 CameraPosition;
			glm::vec4 LightDirection;
			glm::vec4 LightColor;
			glm::vec4 Ambient;
		};

		// Push constants, matches the Draw block in the shaders (128 bytes is the guaranteed Vulkan minimum).
		struct DrawConstants
		{
			glm::mat4 Model;
			glm::vec4 BaseColor;
			glm::vec4 Material; // x metallic, y roughness
			glm::vec4 Emissive;
			glm::vec4 Params;   // x normalScale, y occlusionStrength, z alphaCutoff, w alphaMode (0 opaque, 1 mask, 2 blend)
		};
		static_assert(sizeof(DrawConstants) == 128, "push constants must fit the 128 byte guaranteed minimum");

		struct GpuMesh
		{
			nvrhi::BufferHandle VertexBuffer;
			nvrhi::BufferHandle IndexBuffer;
			uint32_t IndexCount = 0;
		};

		enum class PipelineKind { Opaque = 0, DoubleSided = 1, Blend = 2 };

		struct DrawItem
		{
			const GpuMesh* Mesh = nullptr;
			nvrhi::IBindingSet* Textures = nullptr;
			DrawConstants Constants{};
			PipelineKind Kind = PipelineKind::Opaque;
			float Distance = 0.0f; // from the camera, for sorting blended items
		};

		constexpr nvrhi::Format s_HdrFormat = nvrhi::Format::RGBA16_FLOAT;
		constexpr nvrhi::Format s_DepthFormat = nvrhi::Format::D32;
		constexpr nvrhi::Format s_OutputFormat = nvrhi::Format::RGBA8_UNORM;

		nvrhi::ShaderHandle CreateShader(nvrhi::IDevice* device, nvrhi::ShaderType type, const char* name, const unsigned char* data, size_t size)
		{
			return device->createShader(nvrhi::ShaderDesc().setShaderType(type).setDebugName(name), data, size);
		}

		float AlphaModeValue(AlphaMode mode)
		{
			switch (mode)
			{
				case AlphaMode::Opaque: return 0.0f;
				case AlphaMode::Mask:   return 1.0f;
				case AlphaMode::Blend:  return 2.0f;
			}
			return 0.0f;
		}

	}

	struct Renderer::Impl
	{
		Ref<RenderDevice> Device;
		Settings RenderSettings;
		uint32_t Width = 0;
		uint32_t Height = 0;

		nvrhi::TextureHandle Hdr, Depth, Output;
		nvrhi::FramebufferHandle SceneFramebuffer, OutputFramebuffer;

		nvrhi::BufferHandle FrameBuffer;
		nvrhi::SamplerHandle MaterialSampler, TonemapSampler;

		nvrhi::BindingLayoutHandle SceneLayout, MaterialLayout, TonemapLayout;
		nvrhi::BindingSetHandle SceneBindings, TonemapBindings, DefaultMaterialBindings;
		nvrhi::InputLayoutHandle InputLayout;
		std::array<nvrhi::GraphicsPipelineHandle, 3> ScenePipelines; // indexed by PipelineKind
		nvrhi::GraphicsPipelineHandle TonemapPipeline;

		// Default 1x1 textures used for material slots without a texture.
		nvrhi::TextureHandle WhiteSrgb, WhiteLinear, FlatNormal;

		std::array<GpuMesh, 3> PrimitiveMeshes; // indexed by PrimitiveType
		std::unordered_map<UUID, GpuMesh> AssetMeshes;
		std::map<std::pair<uint64_t, bool>, nvrhi::TextureHandle> AssetTextures; // (texture id, sRGB)
		std::unordered_map<UUID, nvrhi::BindingSetHandle> AssetMaterials;
		std::unordered_set<UUID> WarnedMissing;

		nvrhi::IDevice* Gpu() const { return Device->GetDevice(); }

		GpuMesh UploadMesh(const MeshData& mesh, const std::string& name)
		{
			LM_ASSERT(mesh.IsValid(), "invalid mesh");
			GpuMesh gpu;
			gpu.IndexCount = static_cast<uint32_t>(mesh.Indices.size());

			nvrhi::BufferDesc vertexDesc;
			vertexDesc.byteSize = mesh.Vertices.size() * sizeof(Vertex);
			vertexDesc.isVertexBuffer = true;
			vertexDesc.initialState = nvrhi::ResourceStates::VertexBuffer;
			vertexDesc.keepInitialState = true;
			vertexDesc.debugName = name + " vertices";
			gpu.VertexBuffer = Gpu()->createBuffer(vertexDesc);

			nvrhi::BufferDesc indexDesc;
			indexDesc.byteSize = mesh.Indices.size() * sizeof(uint32_t);
			indexDesc.isIndexBuffer = true;
			indexDesc.initialState = nvrhi::ResourceStates::IndexBuffer;
			indexDesc.keepInitialState = true;
			indexDesc.debugName = name + " indices";
			gpu.IndexBuffer = Gpu()->createBuffer(indexDesc);

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				commandList->writeBuffer(gpu.VertexBuffer, mesh.Vertices.data(), vertexDesc.byteSize);
				commandList->writeBuffer(gpu.IndexBuffer, mesh.Indices.data(), indexDesc.byteSize);
			});
			return gpu;
		}

		nvrhi::TextureHandle UploadTexture(const ImageData& image, bool srgb, const std::string& name)
		{
			std::vector<ImageData> chain = GenerateMipChain(image, srgb);
			if (chain.empty())
				return nullptr;

			nvrhi::TextureDesc desc;
			desc.width = image.Width;
			desc.height = image.Height;
			desc.mipLevels = static_cast<uint32_t>(chain.size());
			desc.format = srgb ? nvrhi::Format::SRGBA8_UNORM : nvrhi::Format::RGBA8_UNORM;
			desc.isShaderResource = true;
			desc.initialState = nvrhi::ResourceStates::ShaderResource;
			desc.keepInitialState = true;
			desc.debugName = name;
			nvrhi::TextureHandle texture = Gpu()->createTexture(desc);

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				for (uint32_t mip = 0; mip < chain.size(); mip++)
					commandList->writeTexture(texture, 0, mip, chain[mip].Pixels.data(), static_cast<size_t>(chain[mip].Width) * 4);
			});
			return texture;
		}

		nvrhi::TextureHandle SolidTexture(uint8_t r, uint8_t g, uint8_t b, uint8_t a, bool srgb, const char* name)
		{
			ImageData image;
			image.Width = image.Height = 1;
			image.BytesPerPixel = 4;
			image.Pixels = { r, g, b, a };
			return UploadTexture(image, srgb, name);
		}

		nvrhi::BindingSetHandle CreateMaterialBindings(nvrhi::ITexture* baseColor, nvrhi::ITexture* metalRough, nvrhi::ITexture* normal,
		                                               nvrhi::ITexture* occlusion, nvrhi::ITexture* emissive)
		{
			return Gpu()->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, baseColor))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(1, metalRough))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(2, normal))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(3, occlusion))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(4, emissive))
				.addItem(nvrhi::BindingSetItem::Sampler(0, MaterialSampler)), MaterialLayout);
		}

		bool Initialize()
		{
			nvrhi::IDevice* gpu = Gpu();

			// --- Targets -------------------------------------------------------------------------------------------
			Hdr = Device->CreateRenderTarget(Width, Height, s_HdrFormat, "SceneHDR");
			Output = Device->CreateRenderTarget(Width, Height, s_OutputFormat, "SceneOutput");

			nvrhi::TextureDesc depthDesc;
			depthDesc.width = Width;
			depthDesc.height = Height;
			depthDesc.format = s_DepthFormat;
			depthDesc.isRenderTarget = true;
			depthDesc.initialState = nvrhi::ResourceStates::DepthWrite;
			depthDesc.keepInitialState = true;
			depthDesc.debugName = "SceneDepth";
			Depth = gpu->createTexture(depthDesc);
			if (!Hdr || !Output || !Depth)
				return false;

			SceneFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Hdr).setDepthAttachment(Depth));
			OutputFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Output));

			// --- Constant buffer and samplers ----------------------------------------------------------------------
			nvrhi::BufferDesc frameDesc;
			frameDesc.byteSize = sizeof(FrameConstants);
			frameDesc.isConstantBuffer = true;
			frameDesc.isVolatile = true;
			frameDesc.maxVersions = 8;
			frameDesc.debugName = "FrameConstants";
			FrameBuffer = gpu->createBuffer(frameDesc);

			TonemapSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			MaterialSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Wrap).setMaxAnisotropy(8.0f));

			// --- Shaders and layouts -------------------------------------------------------------------------------
			nvrhi::ShaderHandle meshVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "mesh.vert", g_Shader_mesh_vert, g_Shader_mesh_vert_size);
			nvrhi::ShaderHandle pbrPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "pbr.frag", g_Shader_pbr_frag, g_Shader_pbr_frag_size);
			nvrhi::ShaderHandle fullscreenVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "fullscreen.vert", g_Shader_fullscreen_vert, g_Shader_fullscreen_vert_size);
			nvrhi::ShaderHandle tonemapPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "tonemap.frag", g_Shader_tonemap_frag, g_Shader_tonemap_frag_size);
			if (!meshVs || !pbrPs || !fullscreenVs || !tonemapPs)
				return false;

			std::array<nvrhi::VertexAttributeDesc, 4> attributes = {
				nvrhi::VertexAttributeDesc().setName("POSITION").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Position)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("NORMAL").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Normal)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("TEXCOORD").setFormat(nvrhi::Format::RG32_FLOAT).setOffset(offsetof(Vertex, UV)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("TANGENT").setFormat(nvrhi::Format::RGBA32_FLOAT).setOffset(offsetof(Vertex, Tangent)).setElementStride(sizeof(Vertex)),
			};
			InputLayout = gpu->createInputLayout(attributes.data(), static_cast<uint32_t>(attributes.size()), meshVs);

			SceneLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(DrawConstants))));
			SceneBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(DrawConstants))), SceneLayout);

			MaterialLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::Pixel)
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(1))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(2))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(3))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(4))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0)));

			WhiteSrgb = SolidTexture(255, 255, 255, 255, true, "DefaultWhiteSrgb");
			WhiteLinear = SolidTexture(255, 255, 255, 255, false, "DefaultWhiteLinear");
			FlatNormal = SolidTexture(128, 128, 255, 255, false, "DefaultFlatNormal");
			if (!WhiteSrgb || !WhiteLinear || !FlatNormal)
				return false;
			DefaultMaterialBindings = CreateMaterialBindings(WhiteSrgb, WhiteLinear, FlatNormal, WhiteLinear, WhiteSrgb);

			TonemapLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(float))));
			TonemapBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, Hdr))
				.addItem(nvrhi::BindingSetItem::Sampler(0, TonemapSampler))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(float))), TonemapLayout);

			// --- Pipelines -----------------------------------------------------------------------------------------
			for (PipelineKind kind : { PipelineKind::Opaque, PipelineKind::DoubleSided, PipelineKind::Blend })
			{
				nvrhi::GraphicsPipelineDesc desc;
				desc.setPrimType(nvrhi::PrimitiveType::TriangleList)
					.setInputLayout(InputLayout)
					.setVertexShader(meshVs)
					.setPixelShader(pbrPs)
					.addBindingLayout(SceneLayout)
					.addBindingLayout(MaterialLayout);
				desc.renderState.depthStencilState.depthTestEnable = true;
				desc.renderState.depthStencilState.depthWriteEnable = kind != PipelineKind::Blend;
				desc.renderState.depthStencilState.depthFunc = nvrhi::ComparisonFunc::Less;
				desc.renderState.rasterState.cullMode = kind == PipelineKind::Opaque ? nvrhi::RasterCullMode::Back : nvrhi::RasterCullMode::None;
				// The projection flips Y for Vulkan, which makes counter-clockwise (world) triangles clockwise in framebuffer space.
				desc.renderState.rasterState.frontCounterClockwise = false;
				if (kind == PipelineKind::Blend)
				{
					nvrhi::BlendState::RenderTarget& target = desc.renderState.blendState.targets[0];
					target.blendEnable = true;
					target.srcBlend = nvrhi::BlendFactor::SrcAlpha;
					target.destBlend = nvrhi::BlendFactor::InvSrcAlpha;
					target.srcBlendAlpha = nvrhi::BlendFactor::One;
					target.destBlendAlpha = nvrhi::BlendFactor::InvSrcAlpha;
				}
				ScenePipelines[static_cast<size_t>(kind)] = gpu->createGraphicsPipeline(desc, SceneFramebuffer->getFramebufferInfo());
				if (!ScenePipelines[static_cast<size_t>(kind)])
					return false;
			}

			nvrhi::GraphicsPipelineDesc tonemapDesc;
			tonemapDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setVertexShader(fullscreenVs)
				.setPixelShader(tonemapPs)
				.addBindingLayout(TonemapLayout);
			tonemapDesc.renderState.depthStencilState.depthTestEnable = false;
			tonemapDesc.renderState.depthStencilState.depthWriteEnable = false;
			tonemapDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::None;
			TonemapPipeline = gpu->createGraphicsPipeline(tonemapDesc, OutputFramebuffer->getFramebufferInfo());
			if (!TonemapPipeline)
				return false;

			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Cube)] = UploadMesh(MeshGenerator::CreateCube(), "Cube");
			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Sphere)] = UploadMesh(MeshGenerator::CreateSphere(48, 24), "Sphere");
			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Plane)] = UploadMesh(MeshGenerator::CreatePlane(), "Plane");
			return true;
		}

		const GpuMesh* GetAssetMesh(UUID id, const AssetManager& assets)
		{
			if (auto it = AssetMeshes.find(id); it != AssetMeshes.end())
				return &it->second;
			const MeshAsset* asset = assets.GetMesh(id);
			if (asset == nullptr || !asset->Data.IsValid() || asset->Data.Indices.empty())
				return nullptr;
			return &(AssetMeshes[id] = UploadMesh(asset->Data, asset->Name));
		}

		nvrhi::ITexture* GetAssetTexture(UUID id, bool srgb, const AssetManager& assets, nvrhi::ITexture* fallback)
		{
			if (!id.IsValid())
				return fallback;
			const auto key = std::make_pair(static_cast<uint64_t>(id), srgb);
			if (auto it = AssetTextures.find(key); it != AssetTextures.end())
				return it->second ? it->second.Get() : fallback;

			const TextureAsset* asset = assets.GetTexture(id);
			nvrhi::TextureHandle texture = asset != nullptr ? UploadTexture(asset->Image, srgb, asset->Name) : nullptr;
			if (!texture)
				LM_WARN("Texture asset {} is missing or unusable; using a default", static_cast<uint64_t>(id));
			AssetTextures[key] = texture; // cache failures too so they are reported once
			return texture ? texture.Get() : fallback;
		}

		nvrhi::IBindingSet* GetAssetMaterialBindings(UUID id, const MaterialAsset& material, const AssetManager& assets)
		{
			if (auto it = AssetMaterials.find(id); it != AssetMaterials.end())
				return it->second;
			nvrhi::BindingSetHandle set = CreateMaterialBindings(
				GetAssetTexture(material.BaseColorTexture, true, assets, WhiteSrgb),
				GetAssetTexture(material.MetallicRoughnessTexture, false, assets, WhiteLinear),
				GetAssetTexture(material.NormalTexture, false, assets, FlatNormal),
				GetAssetTexture(material.OcclusionTexture, false, assets, WhiteLinear),
				GetAssetTexture(material.EmissiveTexture, true, assets, WhiteSrgb));
			AssetMaterials[id] = set;
			return set;
		}
	};

	Ref<Renderer> Renderer::Create(Ref<RenderDevice> device, uint32_t width, uint32_t height)
	{
		if (!device || width == 0 || height == 0)
		{
			LM_ERROR("Renderer needs a device and a non-zero size");
			return nullptr;
		}

		Ref<Renderer> renderer(new Renderer());
		renderer->m_Impl = CreateScope<Impl>();
		renderer->m_Impl->Device = std::move(device);
		renderer->m_Impl->Width = width;
		renderer->m_Impl->Height = height;
		if (!renderer->m_Impl->Initialize())
		{
			LM_ERROR("Failed to create renderer GPU resources");
			return nullptr;
		}
		return renderer;
	}

	Renderer::~Renderer()
	{
		if (m_Impl && m_Impl->Device)
			m_Impl->Device->GetDevice()->waitForIdle();
	}

	Renderer::Settings& Renderer::GetSettings() { return m_Impl->RenderSettings; }
	uint32_t Renderer::GetWidth() const { return m_Impl->Width; }
	uint32_t Renderer::GetHeight() const { return m_Impl->Height; }
	nvrhi::ITexture* Renderer::GetOutput() const { return m_Impl->Output; }
	nvrhi::ITexture* Renderer::GetHdrTarget() const { return m_Impl->Hdr; }
	ImageData Renderer::ReadOutput() { return m_Impl->Device->ReadTexture(m_Impl->Output); }

	bool Renderer::Render(Scene& scene, Entity camera, const AssetManager* assets)
	{
		if (!camera.IsValid() || !camera.HasComponent<CameraComponent>())
		{
			LM_ERROR("Renderer::Render needs a valid camera entity with a CameraComponent");
			return false;
		}

		Impl& impl = *m_Impl;
		entt::registry& registry = scene.GetRegistry();

		// --- Camera ----------------------------------------------------------------------------------------------------
		const CameraComponent& cameraData = camera.GetComponent<CameraComponent>();
		const TransformComponent& cameraTransform = camera.GetComponent<TransformComponent>();
		const glm::mat4 cameraWorld = glm::translate(glm::mat4(1.0f), cameraTransform.Translation) * glm::mat4_cast(glm::quat(cameraTransform.Rotation));

		FrameConstants frame{};
		frame.View = glm::inverse(cameraWorld);
		frame.Proj = glm::perspectiveRH_ZO(cameraData.FovY, static_cast<float>(impl.Width) / static_cast<float>(impl.Height), cameraData.Near, cameraData.Far);
		frame.Proj[1][1] *= -1.0f; // Vulkan clip space has Y pointing down
		frame.CameraPosition = glm::vec4(cameraTransform.Translation, 1.0f);
		frame.Ambient = glm::vec4(impl.RenderSettings.Ambient, 0.0f);

		// --- Light -----------------------------------------------------------------------------------------------------
		frame.LightDirection = glm::vec4(0.0f, -1.0f, 0.0f, 0.0f);
		frame.LightColor = glm::vec4(0.0f);
		for (auto [handle, transform, light] : registry.view<TransformComponent, DirectionalLightComponent>().each())
		{
			const glm::vec3 direction = glm::quat(transform.Rotation) * glm::vec3(0.0f, 0.0f, -1.0f);
			frame.LightDirection = glm::vec4(direction, 0.0f);
			frame.LightColor = glm::vec4(light.Color, light.Intensity);
			break; // a single directional light for now
		}

		// --- Gather draws (uploads any missing GPU resources) ----------------------------------------------------------
		std::vector<DrawItem> draws;
		for (auto [handle, transform, renderer] : registry.view<TransformComponent, MeshRendererComponent>().each())
		{
			DrawItem item;
			if (renderer.MeshAsset.IsValid())
			{
				item.Mesh = assets != nullptr ? impl.GetAssetMesh(renderer.MeshAsset, *assets) : nullptr;
				if (item.Mesh == nullptr)
				{
					if (impl.WarnedMissing.insert(renderer.MeshAsset).second)
						LM_WARN("Mesh asset {} is not available; skipping entities that use it", static_cast<uint64_t>(renderer.MeshAsset));
					continue;
				}
			}
			else
			{
				item.Mesh = &impl.PrimitiveMeshes[static_cast<size_t>(renderer.Primitive)];
			}

			item.Constants.Model = transform.GetTransform();
			item.Textures = impl.DefaultMaterialBindings;
			item.Constants.Params = glm::vec4(1.0f, 1.0f, 0.5f, 0.0f);

			const MaterialAsset* material = renderer.MaterialAsset.IsValid() && assets != nullptr ? assets->GetMaterial(renderer.MaterialAsset) : nullptr;
			if (material != nullptr)
			{
				item.Textures = impl.GetAssetMaterialBindings(renderer.MaterialAsset, *material, *assets);
				item.Constants.BaseColor = material->BaseColor;
				item.Constants.Material = glm::vec4(material->Metallic, material->Roughness, 0.0f, 0.0f);
				item.Constants.Emissive = glm::vec4(material->Emissive, 0.0f);
				item.Constants.Params = glm::vec4(material->NormalScale, material->OcclusionStrength, material->AlphaCutoff, AlphaModeValue(material->Alpha));
				item.Kind = material->Alpha == AlphaMode::Blend ? PipelineKind::Blend : (material->DoubleSided ? PipelineKind::DoubleSided : PipelineKind::Opaque);
			}
			else
			{
				if (renderer.MaterialAsset.IsValid() && impl.WarnedMissing.insert(renderer.MaterialAsset).second)
					LM_WARN("Material asset {} is not available; using the inline material", static_cast<uint64_t>(renderer.MaterialAsset));
				const MaterialData& inlineMaterial = renderer.Material;
				item.Constants.BaseColor = inlineMaterial.BaseColor;
				item.Constants.Material = glm::vec4(inlineMaterial.Metallic, inlineMaterial.Roughness, 0.0f, 0.0f);
				item.Constants.Emissive = glm::vec4(inlineMaterial.Emissive, 0.0f);
				if (inlineMaterial.BaseColor.a < 1.0f)
				{
					item.Constants.Params.w = 2.0f;
					item.Kind = PipelineKind::Blend;
				}
			}
			item.Distance = glm::length(glm::vec3(item.Constants.Model[3]) - cameraTransform.Translation);
			draws.push_back(item);
		}

		// Opaque and masked first (any order), then blended back to front.
		std::stable_partition(draws.begin(), draws.end(), [](const DrawItem& d) { return d.Kind != PipelineKind::Blend; });
		auto firstBlend = std::find_if(draws.begin(), draws.end(), [](const DrawItem& d) { return d.Kind == PipelineKind::Blend; });
		std::stable_sort(firstBlend, draws.end(), [](const DrawItem& a, const DrawItem& b) { return a.Distance > b.Distance; });

		// --- Record ----------------------------------------------------------------------------------------------------
		impl.Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
		{
			commandList->writeBuffer(impl.FrameBuffer, &frame, sizeof(frame));

			const glm::vec3& clear = impl.RenderSettings.ClearColor;
			commandList->clearTextureFloat(impl.Hdr, nvrhi::AllSubresources, nvrhi::Color(clear.r, clear.g, clear.b, 1.0f));
			commandList->clearDepthStencilTexture(impl.Depth, nvrhi::AllSubresources, true, 1.0f, false, 0);

			const nvrhi::Viewport viewport(static_cast<float>(impl.Width), static_cast<float>(impl.Height));
			for (const DrawItem& item : draws)
			{
				nvrhi::GraphicsState state;
				state.setPipeline(impl.ScenePipelines[static_cast<size_t>(item.Kind)])
					.setFramebuffer(impl.SceneFramebuffer)
					.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
					.addBindingSet(impl.SceneBindings)
					.addBindingSet(item.Textures);
				state.vertexBuffers = { { item.Mesh->VertexBuffer, 0, 0 } };
				state.indexBuffer = { item.Mesh->IndexBuffer, nvrhi::Format::R32_UINT, 0 };
				commandList->setGraphicsState(state);
				commandList->setPushConstants(&item.Constants, sizeof(item.Constants));

				nvrhi::DrawArguments args;
				args.vertexCount = item.Mesh->IndexCount;
				commandList->drawIndexed(args);
			}

			nvrhi::GraphicsState tonemapState;
			tonemapState.setPipeline(impl.TonemapPipeline)
				.setFramebuffer(impl.OutputFramebuffer)
				.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
				.addBindingSet(impl.TonemapBindings);
			commandList->setGraphicsState(tonemapState);
			const float exposure = impl.RenderSettings.Exposure;
			commandList->setPushConstants(&exposure, sizeof(exposure));
			nvrhi::DrawArguments fullscreen;
			fullscreen.vertexCount = 3;
			commandList->draw(fullscreen);
		});
		return true;
	}

}
