#include "Lumen/Renderer/Renderer.h"

#include "Lumen/Assets/AssetManager.h"
#include "Lumen/Core/Log.h"
#include "Lumen/Renderer/Environment.h"
#include "Lumen/Renderer/HalfFloat.h"
#include "Lumen/Renderer/Mesh.h"
#include "Lumen/Renderer/MipChain.h"
#include "Lumen/Renderer/Shadow.h"
#include "Lumen/Scene/Scene.h"

#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>

#include <algorithm>
#include <array>
#include <cstddef>
#include <map>
#include <unordered_map>
#include <unordered_set>

// Generated by cmake/Shaders.cmake from Lumen/shaders/.
extern const unsigned char g_Shader_mesh_vert[];
extern const size_t g_Shader_mesh_vert_size;
extern const unsigned char g_Shader_pbr_frag[];
extern const size_t g_Shader_pbr_frag_size;
extern const unsigned char g_Shader_prepass_frag[];
extern const size_t g_Shader_prepass_frag_size;
extern const unsigned char g_Shader_ssao_frag[];
extern const size_t g_Shader_ssao_frag_size;
extern const unsigned char g_Shader_ssao_blur_frag[];
extern const size_t g_Shader_ssao_blur_frag_size;
extern const unsigned char g_Shader_shadow_vert[];
extern const size_t g_Shader_shadow_vert_size;
extern const unsigned char g_Shader_sky_frag[];
extern const size_t g_Shader_sky_frag_size;
extern const unsigned char g_Shader_fullscreen_vert[];
extern const size_t g_Shader_fullscreen_vert_size;
extern const unsigned char g_Shader_tonemap_frag[];
extern const size_t g_Shader_tonemap_frag_size;

namespace Lumen {

	namespace {

		// std140 layout, matches the Frame block in the shaders.
		struct FrameConstants
		{
			glm::mat4 View;
			glm::mat4 Proj;
			glm::mat4 InvViewProj;
			glm::vec4 CameraPosition;
			glm::vec4 LightDirection;
			glm::vec4 LightColor;
			glm::vec4 Ambient;
			glm::vec4 SH[9];
			glm::vec4 EnvParams; // x intensity, y highest specular mip, z environment present, w draw background
			glm::mat4 LightViewProj;
			glm::vec4 ShadowParams;  // x shadows on, y receiver depth bias, z normal offset (world units), w tan(light angular radius)
			glm::vec4 ShadowParams2; // x depth range (world units), y ortho width (world units), z texel size in uv
			glm::vec4 ProjInfo;      // x tan(fovY/2) * aspect, y tan(fovY/2), z near, w far
			glm::vec4 AOParams;      // x radius, y intensity, z power, w enabled
			glm::vec4 ScreenParams;  // x width, y height, z 1/width, w 1/height
		};
		static_assert(sizeof(FrameConstants) == 3 * 64 + 4 * 16 + 9 * 16 + 16 + 64 + 2 * 16 + 3 * 16, "FrameConstants must match frame.glsl (std140)");

		struct ShadowConstants
		{
			glm::mat4 Model;
			glm::mat4 LightViewProj;
		};
		static_assert(sizeof(ShadowConstants) == 128, "shadow push constants must fit the 128 byte guaranteed minimum");

		// Push constants, matches the Draw block in the shaders (128 bytes is the guaranteed Vulkan minimum).
		struct DrawConstants
		{
			glm::mat4 Model;
			glm::vec4 BaseColor;
			glm::vec4 Material; // x metallic, y roughness
			glm::vec4 Emissive;
			glm::vec4 Params;   // x normalScale, y occlusionStrength, z alphaCutoff, w alphaMode (0 opaque, 1 mask, 2 blend)
		};
		static_assert(sizeof(DrawConstants) == 128, "push constants must fit the 128 byte guaranteed minimum");

		struct GpuMesh
		{
			nvrhi::BufferHandle VertexBuffer;
			nvrhi::BufferHandle IndexBuffer;
			uint32_t IndexCount = 0;
			Bounds LocalBounds;
		};

		enum class PipelineKind { Opaque = 0, DoubleSided = 1, Blend = 2 };

		struct DrawItem
		{
			const GpuMesh* Mesh = nullptr;
			nvrhi::IBindingSet* Textures = nullptr;
			DrawConstants Constants{};
			PipelineKind Kind = PipelineKind::Opaque;
			float Distance = 0.0f; // from the camera, for sorting blended items
			bool CastsShadow = false;
			Bounds WorldBounds;
		};

		constexpr nvrhi::Format s_HdrFormat = nvrhi::Format::RGBA16_FLOAT;
		constexpr nvrhi::Format s_DepthFormat = nvrhi::Format::D32;
		constexpr nvrhi::Format s_OutputFormat = nvrhi::Format::RGBA8_UNORM;

		nvrhi::ShaderHandle CreateShader(nvrhi::IDevice* device, nvrhi::ShaderType type, const char* name, const unsigned char* data, size_t size)
		{
			return device->createShader(nvrhi::ShaderDesc().setShaderType(type).setDebugName(name), data, size);
		}

		float AlphaModeValue(AlphaMode mode)
		{
			switch (mode)
			{
				case AlphaMode::Opaque: return 0.0f;
				case AlphaMode::Mask:   return 1.0f;
				case AlphaMode::Blend:  return 2.0f;
			}
			return 0.0f;
		}

	}

	struct Renderer::Impl
	{
		Ref<RenderDevice> Device;
		Settings RenderSettings;
		uint32_t Width = 0;
		uint32_t Height = 0;

		nvrhi::TextureHandle Hdr, Depth, Output;
		nvrhi::FramebufferHandle SceneFramebuffer, OutputFramebuffer;

		nvrhi::BufferHandle FrameBuffer;
		nvrhi::SamplerHandle MaterialSampler, TonemapSampler;

		nvrhi::BindingLayoutHandle SceneLayout, MaterialLayout, TonemapLayout;
		nvrhi::BindingSetHandle SceneBindings, TonemapBindings, DefaultMaterialBindings;
		nvrhi::GraphicsPipelineHandle SkyPipeline;

		// Ambient occlusion: normal/depth prepass -> horizon-based AO -> separable depth-aware blur.
		nvrhi::TextureHandle AoDepth, NormalTarget, AoRaw, AoTemp, AoFinal;
		nvrhi::FramebufferHandle PrepassFramebuffer, AoRawFramebuffer, AoTempFramebuffer, AoFinalFramebuffer;
		nvrhi::SamplerHandle PointSampler, AoSampler;
		nvrhi::BindingLayoutHandle PrepassLayout, AoLayout, BlurLayout;
		nvrhi::BindingSetHandle PrepassBindings, AoBindings, BlurHBindings, BlurVBindings;
		std::array<nvrhi::GraphicsPipelineHandle, 2> PrepassPipelines; // Opaque, DoubleSided
		nvrhi::GraphicsPipelineHandle AoPipeline, BlurHPipeline, BlurVPipeline;

		// Shadow mapping.
		uint32_t ShadowSize = 2048;
		nvrhi::TextureHandle ShadowMap;
		nvrhi::SamplerHandle ShadowSampler;
		nvrhi::FramebufferHandle ShadowFramebuffer;
		nvrhi::BindingLayoutHandle ShadowLayout;
		nvrhi::BindingSetHandle ShadowBindings;
		nvrhi::GraphicsPipelineHandle ShadowPipeline;

		// Image-based lighting resources (dummies keep the bindings valid when no environment is set).
		Ref<const Environment> CurrentEnvironment;
		nvrhi::TextureHandle EnvSpecular, EnvBackground, BrdfLut;
		nvrhi::TextureHandle DummyCube, DummyBackground, DummyLut;
		nvrhi::SamplerHandle EnvSampler, SkySampler;
		std::array<glm::vec4, 9> EnvSH{};
		float EnvMaxMip = 0.0f;
		nvrhi::InputLayoutHandle InputLayout;
		std::array<nvrhi::GraphicsPipelineHandle, 3> ScenePipelines; // indexed by PipelineKind
		nvrhi::GraphicsPipelineHandle TonemapPipeline;

		// Default 1x1 textures used for material slots without a texture.
		nvrhi::TextureHandle WhiteSrgb, WhiteLinear, FlatNormal;

		std::array<GpuMesh, 3> PrimitiveMeshes; // indexed by PrimitiveType
		std::unordered_map<UUID, GpuMesh> AssetMeshes;
		std::map<std::pair<uint64_t, bool>, nvrhi::TextureHandle> AssetTextures; // (texture id, sRGB)
		std::unordered_map<UUID, nvrhi::BindingSetHandle> AssetMaterials;
		std::unordered_set<UUID> WarnedMissing;

		nvrhi::IDevice* Gpu() const { return Device->GetDevice(); }

		GpuMesh UploadMesh(const MeshData& mesh, const std::string& name)
		{
			LM_ASSERT(mesh.IsValid(), "invalid mesh");
			GpuMesh gpu;
			gpu.IndexCount = static_cast<uint32_t>(mesh.Indices.size());
			for (const Vertex& v : mesh.Vertices)
				gpu.LocalBounds.Expand(v.Position);

			nvrhi::BufferDesc vertexDesc;
			vertexDesc.byteSize = mesh.Vertices.size() * sizeof(Vertex);
			vertexDesc.isVertexBuffer = true;
			vertexDesc.initialState = nvrhi::ResourceStates::VertexBuffer;
			vertexDesc.keepInitialState = true;
			vertexDesc.debugName = name + " vertices";
			gpu.VertexBuffer = Gpu()->createBuffer(vertexDesc);

			nvrhi::BufferDesc indexDesc;
			indexDesc.byteSize = mesh.Indices.size() * sizeof(uint32_t);
			indexDesc.isIndexBuffer = true;
			indexDesc.initialState = nvrhi::ResourceStates::IndexBuffer;
			indexDesc.keepInitialState = true;
			indexDesc.debugName = name + " indices";
			gpu.IndexBuffer = Gpu()->createBuffer(indexDesc);

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				commandList->writeBuffer(gpu.VertexBuffer, mesh.Vertices.data(), vertexDesc.byteSize);
				commandList->writeBuffer(gpu.IndexBuffer, mesh.Indices.data(), indexDesc.byteSize);
			});
			return gpu;
		}

		nvrhi::TextureHandle UploadTexture(const ImageData& image, bool srgb, const std::string& name)
		{
			std::vector<ImageData> chain = GenerateMipChain(image, srgb);
			if (chain.empty())
				return nullptr;

			nvrhi::TextureDesc desc;
			desc.width = image.Width;
			desc.height = image.Height;
			desc.mipLevels = static_cast<uint32_t>(chain.size());
			desc.format = srgb ? nvrhi::Format::SRGBA8_UNORM : nvrhi::Format::RGBA8_UNORM;
			desc.isShaderResource = true;
			desc.initialState = nvrhi::ResourceStates::ShaderResource;
			desc.keepInitialState = true;
			desc.debugName = name;
			nvrhi::TextureHandle texture = Gpu()->createTexture(desc);

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				for (uint32_t mip = 0; mip < chain.size(); mip++)
					commandList->writeTexture(texture, 0, mip, chain[mip].Pixels.data(), static_cast<size_t>(chain[mip].Width) * 4);
			});
			return texture;
		}

		nvrhi::TextureHandle SolidTexture(uint8_t r, uint8_t g, uint8_t b, uint8_t a, bool srgb, const char* name)
		{
			ImageData image;
			image.Width = image.Height = 1;
			image.BytesPerPixel = 4;
			image.Pixels = { r, g, b, a };
			return UploadTexture(image, srgb, name);
		}

		nvrhi::BindingSetHandle CreateMaterialBindings(nvrhi::ITexture* baseColor, nvrhi::ITexture* metalRough, nvrhi::ITexture* normal,
		                                               nvrhi::ITexture* occlusion, nvrhi::ITexture* emissive)
		{
			return Gpu()->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::Texture_SRV(8, baseColor))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(9, metalRough))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(10, normal))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(11, occlusion))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(12, emissive))
				.addItem(nvrhi::BindingSetItem::Sampler(8, MaterialSampler)), MaterialLayout);
		}

		nvrhi::TextureHandle CreateHalfTexture(uint32_t width, uint32_t height, uint32_t arraySize, uint32_t mips, nvrhi::Format format, const char* name)
		{
			nvrhi::TextureDesc desc;
			desc.width = width;
			desc.height = height;
			desc.arraySize = arraySize;
			desc.mipLevels = mips;
			desc.format = format;
			desc.dimension = arraySize == 6 ? nvrhi::TextureDimension::TextureCube : nvrhi::TextureDimension::Texture2D;
			desc.isShaderResource = true;
			desc.initialState = nvrhi::ResourceStates::ShaderResource;
			desc.keepInitialState = true;
			desc.debugName = name;
			return Gpu()->createTexture(desc);
		}

		static std::vector<uint16_t> ToHalf(const float* data, size_t count)
		{
			std::vector<uint16_t> out(count);
			for (size_t i = 0; i < count; i++)
				out[i] = FloatToHalf(data[i]);
			return out;
		}

		// (Re)creates the set-0 bindings from the current environment textures or the dummies.
		void RebuildSceneBindings()
		{
			nvrhi::ITexture* specular = EnvSpecular ? EnvSpecular.Get() : DummyCube.Get();
			nvrhi::ITexture* lut = BrdfLut ? BrdfLut.Get() : DummyLut.Get();
			nvrhi::ITexture* background = EnvBackground ? EnvBackground.Get() : DummyBackground.Get();
			SceneBindings = Gpu()->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(DrawConstants)))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, specular, nvrhi::Format::UNKNOWN, nvrhi::AllSubresources, nvrhi::TextureDimension::TextureCube))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(1, lut))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(2, background))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(3, ShadowMap))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(4, AoFinal))
				.addItem(nvrhi::BindingSetItem::Sampler(0, EnvSampler))
				.addItem(nvrhi::BindingSetItem::Sampler(1, SkySampler))
				.addItem(nvrhi::BindingSetItem::Sampler(2, ShadowSampler))
				.addItem(nvrhi::BindingSetItem::Sampler(3, AoSampler)), SceneLayout);
		}

		bool SetEnvironmentImpl(Ref<const Environment> environment)
		{
			if (!environment)
			{
				CurrentEnvironment = nullptr;
				EnvSpecular = nullptr;
				EnvBackground = nullptr;
				RebuildSceneBindings();
				return true;
			}

			const CubeMapData& cube = environment->Specular;
			const ImageIO::HdrImage& background = environment->Background;
			if (cube.Size == 0 || cube.MipCount == 0 || background.Width == 0 || background.Height == 0)
			{
				LM_ERROR("Environment is empty");
				return false;
			}

			nvrhi::TextureHandle specular = CreateHalfTexture(cube.Size, cube.Size, 6, cube.MipCount, nvrhi::Format::RGBA16_FLOAT, "EnvSpecular");
			nvrhi::TextureHandle sky = CreateHalfTexture(background.Width, background.Height, 1, 1, nvrhi::Format::RGBA16_FLOAT, "EnvBackground");
			if (!specular || !sky)
				return false;

			if (!BrdfLut)
			{
				constexpr uint32_t lutSize = 128;
				const std::vector<float> lut = EnvironmentBuilder::BuildBrdfLut(lutSize, 128);
				nvrhi::TextureHandle lutTexture = CreateHalfTexture(lutSize, lutSize, 1, 1, nvrhi::Format::RG16_FLOAT, "BrdfLut");
				if (!lutTexture)
					return false;
				const std::vector<uint16_t> half = ToHalf(lut.data(), lut.size());
				Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
				{
					commandList->writeTexture(lutTexture, 0, 0, half.data(), static_cast<size_t>(lutSize) * 4);
				});
				BrdfLut = lutTexture;
			}

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				for (uint32_t mip = 0; mip < cube.MipCount; mip++)
				{
					const uint32_t size = cube.MipSize(mip);
					for (uint32_t face = 0; face < 6; face++)
					{
						const std::vector<uint16_t> half = ToHalf(cube.Pixels.data() + cube.Offset(mip, face), static_cast<size_t>(size) * size * 4);
						commandList->writeTexture(specular, face, mip, half.data(), static_cast<size_t>(size) * 8);
					}
				}
				const std::vector<uint16_t> half = ToHalf(background.Pixels.data(), background.Pixels.size());
				commandList->writeTexture(sky, 0, 0, half.data(), static_cast<size_t>(background.Width) * 8);
			});

			CurrentEnvironment = std::move(environment);
			EnvSpecular = specular;
			EnvBackground = sky;
			EnvMaxMip = static_cast<float>(cube.MipCount - 1);
			for (size_t i = 0; i < 9; i++)
				EnvSH[i] = glm::vec4(CurrentEnvironment->IrradianceSH[i], 0.0f);
			RebuildSceneBindings();
			return true;
		}

		bool Initialize()
		{
			nvrhi::IDevice* gpu = Gpu();

			// --- Targets -------------------------------------------------------------------------------------------
			Hdr = Device->CreateRenderTarget(Width, Height, s_HdrFormat, "SceneHDR");
			Output = Device->CreateRenderTarget(Width, Height, s_OutputFormat, "SceneOutput");

			nvrhi::TextureDesc depthDesc;
			depthDesc.width = Width;
			depthDesc.height = Height;
			depthDesc.format = s_DepthFormat;
			depthDesc.isRenderTarget = true;
			depthDesc.initialState = nvrhi::ResourceStates::DepthWrite;
			depthDesc.keepInitialState = true;
			depthDesc.debugName = "SceneDepth";
			Depth = gpu->createTexture(depthDesc);
			if (!Hdr || !Output || !Depth)
				return false;

			SceneFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Hdr).setDepthAttachment(Depth));
			OutputFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Output));

			// --- Constant buffer and samplers ----------------------------------------------------------------------
			nvrhi::BufferDesc frameDesc;
			frameDesc.byteSize = sizeof(FrameConstants);
			frameDesc.isConstantBuffer = true;
			frameDesc.isVolatile = true;
			frameDesc.maxVersions = 8;
			frameDesc.debugName = "FrameConstants";
			FrameBuffer = gpu->createBuffer(frameDesc);

			TonemapSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			EnvSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			SkySampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true)
				.setAddressU(nvrhi::SamplerAddressMode::Wrap).setAddressV(nvrhi::SamplerAddressMode::Clamp).setAddressW(nvrhi::SamplerAddressMode::Clamp));
			MaterialSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Wrap).setMaxAnisotropy(8.0f));

			// --- Shaders and layouts -------------------------------------------------------------------------------
			nvrhi::ShaderHandle meshVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "mesh.vert", g_Shader_mesh_vert, g_Shader_mesh_vert_size);
			nvrhi::ShaderHandle pbrPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "pbr.frag", g_Shader_pbr_frag, g_Shader_pbr_frag_size);
			nvrhi::ShaderHandle skyPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "sky.frag", g_Shader_sky_frag, g_Shader_sky_frag_size);
			nvrhi::ShaderHandle fullscreenVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "fullscreen.vert", g_Shader_fullscreen_vert, g_Shader_fullscreen_vert_size);
			nvrhi::ShaderHandle tonemapPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "tonemap.frag", g_Shader_tonemap_frag, g_Shader_tonemap_frag_size);
			if (!meshVs || !pbrPs || !skyPs || !fullscreenVs || !tonemapPs)
				return false;

			std::array<nvrhi::VertexAttributeDesc, 4> attributes = {
				nvrhi::VertexAttributeDesc().setName("POSITION").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Position)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("NORMAL").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Normal)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("TEXCOORD").setFormat(nvrhi::Format::RG32_FLOAT).setOffset(offsetof(Vertex, UV)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("TANGENT").setFormat(nvrhi::Format::RGBA32_FLOAT).setOffset(offsetof(Vertex, Tangent)).setElementStride(sizeof(Vertex)),
			};
			InputLayout = gpu->createInputLayout(attributes.data(), static_cast<uint32_t>(attributes.size()), meshVs);

			SceneLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(DrawConstants)))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0)) // specular cube
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(1)) // BRDF LUT
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(2)) // background
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(3)) // shadow map
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(4)) // ambient occlusion
				.addItem(nvrhi::BindingLayoutItem::Sampler(0))
				.addItem(nvrhi::BindingLayoutItem::Sampler(1))
				.addItem(nvrhi::BindingLayoutItem::Sampler(2))
				.addItem(nvrhi::BindingLayoutItem::Sampler(3)));

			// Shadow map and its depth-only pass.
			nvrhi::TextureDesc shadowDesc;
			shadowDesc.width = ShadowSize;
			shadowDesc.height = ShadowSize;
			shadowDesc.format = nvrhi::Format::D32;
			shadowDesc.isRenderTarget = true;
			shadowDesc.isShaderResource = true;
			shadowDesc.initialState = nvrhi::ResourceStates::ShaderResource;
			shadowDesc.keepInitialState = true;
			shadowDesc.debugName = "ShadowMap";
			ShadowMap = gpu->createTexture(shadowDesc);
			ShadowSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(false).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			if (!ShadowMap || !ShadowSampler)
				return false;
			ShadowFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().setDepthAttachment(ShadowMap));

			// Ambient occlusion targets and passes.
			nvrhi::TextureDesc aoDepthDesc;
			aoDepthDesc.width = Width;
			aoDepthDesc.height = Height;
			aoDepthDesc.format = nvrhi::Format::D32;
			aoDepthDesc.isRenderTarget = true;
			aoDepthDesc.isShaderResource = true;
			aoDepthDesc.initialState = nvrhi::ResourceStates::ShaderResource;
			aoDepthDesc.keepInitialState = true;
			aoDepthDesc.debugName = "AoDepth";
			AoDepth = gpu->createTexture(aoDepthDesc);
			NormalTarget = Device->CreateRenderTarget(Width, Height, nvrhi::Format::RGBA16_FLOAT, "AoNormals");
			AoRaw = Device->CreateRenderTarget(Width, Height, nvrhi::Format::R8_UNORM, "AoRaw");
			AoTemp = Device->CreateRenderTarget(Width, Height, nvrhi::Format::R8_UNORM, "AoTemp");
			AoFinal = Device->CreateRenderTarget(Width, Height, nvrhi::Format::R8_UNORM, "AoFinal");
			PointSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(false).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			AoSampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));
			if (!AoDepth || !NormalTarget || !AoRaw || !AoTemp || !AoFinal || !PointSampler || !AoSampler)
				return false;
			PrepassFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(NormalTarget).setDepthAttachment(AoDepth));
			AoRawFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(AoRaw));
			AoTempFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(AoTemp));
			AoFinalFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(AoFinal));

			// Dummies keep the environment bindings valid while no environment is set.
			DummyCube = CreateHalfTexture(1, 1, 6, 1, nvrhi::Format::RGBA16_FLOAT, "DummyCube");
			DummyBackground = CreateHalfTexture(1, 1, 1, 1, nvrhi::Format::RGBA16_FLOAT, "DummyBackground");
			DummyLut = CreateHalfTexture(1, 1, 1, 1, nvrhi::Format::RG16_FLOAT, "DummyLut");
			if (!DummyCube || !DummyBackground || !DummyLut)
				return false;
			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				const uint16_t zeros[4] = { 0, 0, 0, 0 };
				for (uint32_t face = 0; face < 6; face++)
					commandList->writeTexture(DummyCube, face, 0, zeros, 8);
				commandList->writeTexture(DummyBackground, 0, 0, zeros, 8);
				commandList->writeTexture(DummyLut, 0, 0, zeros, 4);
			});
			RebuildSceneBindings();

			MaterialLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::Pixel)
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(8))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(9))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(10))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(11))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(12))
				.addItem(nvrhi::BindingLayoutItem::Sampler(8)));

			WhiteSrgb = SolidTexture(255, 255, 255, 255, true, "DefaultWhiteSrgb");
			WhiteLinear = SolidTexture(255, 255, 255, 255, false, "DefaultWhiteLinear");
			FlatNormal = SolidTexture(128, 128, 255, 255, false, "DefaultFlatNormal");
			if (!WhiteSrgb || !WhiteLinear || !FlatNormal)
				return false;
			DefaultMaterialBindings = CreateMaterialBindings(WhiteSrgb, WhiteLinear, FlatNormal, WhiteLinear, WhiteSrgb);

			TonemapLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(float))));
			TonemapBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, Hdr))
				.addItem(nvrhi::BindingSetItem::Sampler(0, TonemapSampler))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(float))), TonemapLayout);

			// --- Pipelines -----------------------------------------------------------------------------------------
			for (PipelineKind kind : { PipelineKind::Opaque, PipelineKind::DoubleSided, PipelineKind::Blend })
			{
				nvrhi::GraphicsPipelineDesc desc;
				desc.setPrimType(nvrhi::PrimitiveType::TriangleList)
					.setInputLayout(InputLayout)
					.setVertexShader(meshVs)
					.setPixelShader(pbrPs)
					.addBindingLayout(SceneLayout)
					.addBindingLayout(MaterialLayout);
				desc.renderState.depthStencilState.depthTestEnable = true;
				desc.renderState.depthStencilState.depthWriteEnable = kind != PipelineKind::Blend;
				desc.renderState.depthStencilState.depthFunc = nvrhi::ComparisonFunc::Less;
				desc.renderState.rasterState.cullMode = kind == PipelineKind::Opaque ? nvrhi::RasterCullMode::Back : nvrhi::RasterCullMode::None;
				desc.renderState.rasterState.frontCounterClockwise = true; // glTF and our primitives are counter-clockwise
				if (kind == PipelineKind::Blend)
				{
					nvrhi::BlendState::RenderTarget& target = desc.renderState.blendState.targets[0];
					target.blendEnable = true;
					target.srcBlend = nvrhi::BlendFactor::SrcAlpha;
					target.destBlend = nvrhi::BlendFactor::InvSrcAlpha;
					target.srcBlendAlpha = nvrhi::BlendFactor::One;
					target.destBlendAlpha = nvrhi::BlendFactor::InvSrcAlpha;
				}
				ScenePipelines[static_cast<size_t>(kind)] = gpu->createGraphicsPipeline(desc, SceneFramebuffer->getFramebufferInfo());
				if (!ScenePipelines[static_cast<size_t>(kind)])
					return false;
			}

			nvrhi::GraphicsPipelineDesc tonemapDesc;
			tonemapDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setVertexShader(fullscreenVs)
				.setPixelShader(tonemapPs)
				.addBindingLayout(TonemapLayout);
			tonemapDesc.renderState.depthStencilState.depthTestEnable = false;
			tonemapDesc.renderState.depthStencilState.depthWriteEnable = false;
			tonemapDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::None;
			TonemapPipeline = gpu->createGraphicsPipeline(tonemapDesc, OutputFramebuffer->getFramebufferInfo());
			if (!TonemapPipeline)
				return false;

			nvrhi::GraphicsPipelineDesc skyDesc;
			skyDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setVertexShader(fullscreenVs)
				.setPixelShader(skyPs)
				.addBindingLayout(SceneLayout);
			skyDesc.renderState.depthStencilState.depthTestEnable = false;
			skyDesc.renderState.depthStencilState.depthWriteEnable = false;
			skyDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::None;
			SkyPipeline = gpu->createGraphicsPipeline(skyDesc, SceneFramebuffer->getFramebufferInfo());
			if (!SkyPipeline)
				return false;

			nvrhi::ShaderHandle shadowVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "shadow.vert", g_Shader_shadow_vert, g_Shader_shadow_vert_size);
			ShadowLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::Vertex)
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(ShadowConstants))));
			ShadowBindings = gpu->createBindingSet(nvrhi::BindingSetDesc().addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(ShadowConstants))), ShadowLayout);
			nvrhi::GraphicsPipelineDesc shadowPipelineDesc;
			shadowPipelineDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setInputLayout(InputLayout)
				.setVertexShader(shadowVs)
				.addBindingLayout(ShadowLayout);
			shadowPipelineDesc.renderState.depthStencilState.depthTestEnable = true;
			shadowPipelineDesc.renderState.depthStencilState.depthWriteEnable = true;
			shadowPipelineDesc.renderState.depthStencilState.depthFunc = nvrhi::ComparisonFunc::Less;
			shadowPipelineDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::Back;
			shadowPipelineDesc.renderState.rasterState.frontCounterClockwise = true;
			shadowPipelineDesc.renderState.rasterState.depthBias = 2;
			shadowPipelineDesc.renderState.rasterState.slopeScaledDepthBias = 2.0f;
			ShadowPipeline = gpu->createGraphicsPipeline(shadowPipelineDesc, ShadowFramebuffer->getFramebufferInfo());
			if (!ShadowPipeline)
				return false;

			// --- Ambient occlusion pipelines ---------------------------------------------------------------------------
			nvrhi::ShaderHandle prepassPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "prepass.frag", g_Shader_prepass_frag, g_Shader_prepass_frag_size);
			nvrhi::ShaderHandle ssaoPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "ssao.frag", g_Shader_ssao_frag, g_Shader_ssao_frag_size);
			nvrhi::ShaderHandle blurPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "ssao_blur.frag", g_Shader_ssao_blur_frag, g_Shader_ssao_blur_frag_size);
			if (!prepassPs || !ssaoPs || !blurPs)
				return false;

			PrepassLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(DrawConstants))));
			PrepassBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(DrawConstants))), PrepassLayout);

			AoLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(1))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0)));
			AoBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, AoDepth))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(1, NormalTarget))
				.addItem(nvrhi::BindingSetItem::Sampler(0, PointSampler)), AoLayout);

			BlurLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(1))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(glm::vec2))));
			BlurHBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, AoRaw))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(1, AoDepth))
				.addItem(nvrhi::BindingSetItem::Sampler(0, PointSampler))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(glm::vec2))), BlurLayout);
			BlurVBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, AoTemp))
				.addItem(nvrhi::BindingSetItem::Texture_SRV(1, AoDepth))
				.addItem(nvrhi::BindingSetItem::Sampler(0, PointSampler))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(glm::vec2))), BlurLayout);

			for (PipelineKind kind : { PipelineKind::Opaque, PipelineKind::DoubleSided })
			{
				nvrhi::GraphicsPipelineDesc desc;
				desc.setPrimType(nvrhi::PrimitiveType::TriangleList)
					.setInputLayout(InputLayout)
					.setVertexShader(meshVs)
					.setPixelShader(prepassPs)
					.addBindingLayout(PrepassLayout);
				desc.renderState.depthStencilState.depthTestEnable = true;
				desc.renderState.depthStencilState.depthWriteEnable = true;
				desc.renderState.depthStencilState.depthFunc = nvrhi::ComparisonFunc::Less;
				desc.renderState.rasterState.cullMode = kind == PipelineKind::Opaque ? nvrhi::RasterCullMode::Back : nvrhi::RasterCullMode::None;
				desc.renderState.rasterState.frontCounterClockwise = true;
				PrepassPipelines[static_cast<size_t>(kind)] = gpu->createGraphicsPipeline(desc, PrepassFramebuffer->getFramebufferInfo());
				if (!PrepassPipelines[static_cast<size_t>(kind)])
					return false;
			}

			auto makeFullscreenPipeline = [&](nvrhi::IShader* pixelShader, nvrhi::IBindingLayout* layout, nvrhi::IFramebuffer* framebuffer)
			{
				nvrhi::GraphicsPipelineDesc desc;
				desc.setPrimType(nvrhi::PrimitiveType::TriangleList)
					.setVertexShader(fullscreenVs)
					.setPixelShader(pixelShader)
					.addBindingLayout(layout);
				desc.renderState.depthStencilState.depthTestEnable = false;
				desc.renderState.depthStencilState.depthWriteEnable = false;
				desc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::None;
				return gpu->createGraphicsPipeline(desc, framebuffer->getFramebufferInfo());
			};
			AoPipeline = makeFullscreenPipeline(ssaoPs, AoLayout, AoRawFramebuffer);
			BlurHPipeline = makeFullscreenPipeline(blurPs, BlurLayout, AoTempFramebuffer);
			BlurVPipeline = makeFullscreenPipeline(blurPs, BlurLayout, AoFinalFramebuffer);
			if (!AoPipeline || !BlurHPipeline || !BlurVPipeline)
				return false;

			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Cube)] = UploadMesh(MeshGenerator::CreateCube(), "Cube");
			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Sphere)] = UploadMesh(MeshGenerator::CreateSphere(48, 24), "Sphere");
			PrimitiveMeshes[static_cast<size_t>(PrimitiveType::Plane)] = UploadMesh(MeshGenerator::CreatePlane(), "Plane");
			return true;
		}

		const GpuMesh* GetAssetMesh(UUID id, const AssetManager& assets)
		{
			if (auto it = AssetMeshes.find(id); it != AssetMeshes.end())
				return &it->second;
			const MeshAsset* asset = assets.GetMesh(id);
			if (asset == nullptr || !asset->Data.IsValid() || asset->Data.Indices.empty())
				return nullptr;
			return &(AssetMeshes[id] = UploadMesh(asset->Data, asset->Name));
		}

		nvrhi::ITexture* GetAssetTexture(UUID id, bool srgb, const AssetManager& assets, nvrhi::ITexture* fallback)
		{
			if (!id.IsValid())
				return fallback;
			const auto key = std::make_pair(static_cast<uint64_t>(id), srgb);
			if (auto it = AssetTextures.find(key); it != AssetTextures.end())
				return it->second ? it->second.Get() : fallback;

			const TextureAsset* asset = assets.GetTexture(id);
			nvrhi::TextureHandle texture = asset != nullptr ? UploadTexture(asset->Image, srgb, asset->Name) : nullptr;
			if (!texture)
				LM_WARN("Texture asset {} is missing or unusable; using a default", static_cast<uint64_t>(id));
			AssetTextures[key] = texture; // cache failures too so they are reported once
			return texture ? texture.Get() : fallback;
		}

		nvrhi::IBindingSet* GetAssetMaterialBindings(UUID id, const MaterialAsset& material, const AssetManager& assets)
		{
			if (auto it = AssetMaterials.find(id); it != AssetMaterials.end())
				return it->second;
			nvrhi::BindingSetHandle set = CreateMaterialBindings(
				GetAssetTexture(material.BaseColorTexture, true, assets, WhiteSrgb),
				GetAssetTexture(material.MetallicRoughnessTexture, false, assets, WhiteLinear),
				GetAssetTexture(material.NormalTexture, false, assets, FlatNormal),
				GetAssetTexture(material.OcclusionTexture, false, assets, WhiteLinear),
				GetAssetTexture(material.EmissiveTexture, true, assets, WhiteSrgb));
			AssetMaterials[id] = set;
			return set;
		}
	};

	Ref<Renderer> Renderer::Create(Ref<RenderDevice> device, uint32_t width, uint32_t height, uint32_t shadowMapSize)
	{
		if (!device || width == 0 || height == 0 || shadowMapSize < 256 || shadowMapSize > 8192)
		{
			LM_ERROR("Renderer needs a device, a non-zero size and a shadow map size between 256 and 8192");
			return nullptr;
		}

		Ref<Renderer> renderer(new Renderer());
		renderer->m_Impl = CreateScope<Impl>();
		renderer->m_Impl->Device = std::move(device);
		renderer->m_Impl->Width = width;
		renderer->m_Impl->Height = height;
		renderer->m_Impl->ShadowSize = shadowMapSize;
		if (!renderer->m_Impl->Initialize())
		{
			LM_ERROR("Failed to create renderer GPU resources");
			return nullptr;
		}
		return renderer;
	}

	Renderer::~Renderer()
	{
		if (m_Impl && m_Impl->Device)
			m_Impl->Device->GetDevice()->waitForIdle();
	}

	Renderer::Settings& Renderer::GetSettings() { return m_Impl->RenderSettings; }
	bool Renderer::SetEnvironment(Ref<const Environment> environment) { return m_Impl->SetEnvironmentImpl(std::move(environment)); }
	bool Renderer::HasEnvironment() const { return m_Impl->CurrentEnvironment != nullptr; }
	uint32_t Renderer::GetWidth() const { return m_Impl->Width; }
	uint32_t Renderer::GetHeight() const { return m_Impl->Height; }
	nvrhi::ITexture* Renderer::GetOutput() const { return m_Impl->Output; }
	nvrhi::ITexture* Renderer::GetHdrTarget() const { return m_Impl->Hdr; }
	nvrhi::ITexture* Renderer::GetAmbientOcclusion() const { return m_Impl->AoFinal; }
	ImageData Renderer::ReadOutput() { return m_Impl->Device->ReadTexture(m_Impl->Output); }

	bool Renderer::Render(Scene& scene, Entity camera, const AssetManager* assets)
	{
		if (!camera.IsValid() || !camera.HasComponent<CameraComponent>())
		{
			LM_ERROR("Renderer::Render needs a valid camera entity with a CameraComponent");
			return false;
		}

		Impl& impl = *m_Impl;
		entt::registry& registry = scene.GetRegistry();

		// --- Camera ----------------------------------------------------------------------------------------------------
		const CameraComponent& cameraData = camera.GetComponent<CameraComponent>();
		const TransformComponent& cameraTransform = camera.GetComponent<TransformComponent>();
		const glm::mat4 cameraWorld = glm::translate(glm::mat4(1.0f), cameraTransform.Translation) * glm::mat4_cast(glm::quat(cameraTransform.Rotation));

		FrameConstants frame{};
		frame.View = glm::inverse(cameraWorld);
		frame.Proj = glm::perspectiveRH_ZO(cameraData.FovY, static_cast<float>(impl.Width) / static_cast<float>(impl.Height), cameraData.Near, cameraData.Far);
		// No Y flip: nvrhi's Vulkan backend flips the viewport itself, so clip space is +Y up like D3D/OpenGL.
		frame.InvViewProj = glm::inverse(frame.Proj * frame.View);
		frame.CameraPosition = glm::vec4(cameraTransform.Translation, 1.0f);
		frame.Ambient = glm::vec4(impl.RenderSettings.Ambient, 0.0f);
		const bool hasEnvironment = impl.CurrentEnvironment != nullptr;
		frame.EnvParams = glm::vec4(impl.RenderSettings.EnvironmentIntensity, impl.EnvMaxMip, hasEnvironment ? 1.0f : 0.0f,
		                            hasEnvironment && impl.RenderSettings.ShowBackground ? 1.0f : 0.0f);
		for (size_t i = 0; i < 9; i++)
			frame.SH[i] = hasEnvironment ? impl.EnvSH[i] : glm::vec4(0.0f);

		// --- Light -----------------------------------------------------------------------------------------------------
		frame.LightDirection = glm::vec4(0.0f, -1.0f, 0.0f, 0.0f);
		frame.LightColor = glm::vec4(0.0f);
		bool hasLight = false;
		for (auto [handle, transform, light] : registry.view<TransformComponent, DirectionalLightComponent>().each())
		{
			const glm::vec3 direction = glm::quat(transform.Rotation) * glm::vec3(0.0f, 0.0f, -1.0f);
			hasLight = light.Intensity > 0.0f;
			frame.LightDirection = glm::vec4(direction, 0.0f);
			frame.LightColor = glm::vec4(light.Color, light.Intensity);
			break; // a single directional light for now
		}

		// --- Gather draws (uploads any missing GPU resources) ----------------------------------------------------------
		std::vector<DrawItem> draws;
		for (auto [handle, transform, renderer] : registry.view<TransformComponent, MeshRendererComponent>().each())
		{
			DrawItem item;
			if (renderer.MeshAsset.IsValid())
			{
				item.Mesh = assets != nullptr ? impl.GetAssetMesh(renderer.MeshAsset, *assets) : nullptr;
				if (item.Mesh == nullptr)
				{
					if (impl.WarnedMissing.insert(renderer.MeshAsset).second)
						LM_WARN("Mesh asset {} is not available; skipping entities that use it", static_cast<uint64_t>(renderer.MeshAsset));
					continue;
				}
			}
			else
			{
				item.Mesh = &impl.PrimitiveMeshes[static_cast<size_t>(renderer.Primitive)];
			}

			item.Constants.Model = transform.GetTransform();
			item.Textures = impl.DefaultMaterialBindings;
			item.Constants.Params = glm::vec4(1.0f, 1.0f, 0.5f, 0.0f);

			const MaterialAsset* material = renderer.MaterialAsset.IsValid() && assets != nullptr ? assets->GetMaterial(renderer.MaterialAsset) : nullptr;
			if (material != nullptr)
			{
				item.Textures = impl.GetAssetMaterialBindings(renderer.MaterialAsset, *material, *assets);
				item.Constants.BaseColor = material->BaseColor;
				item.Constants.Material = glm::vec4(material->Metallic, material->Roughness, 0.0f, 0.0f);
				item.Constants.Emissive = glm::vec4(material->Emissive, 0.0f);
				item.Constants.Params = glm::vec4(material->NormalScale, material->OcclusionStrength, material->AlphaCutoff, AlphaModeValue(material->Alpha));
				item.Kind = material->Alpha == AlphaMode::Blend ? PipelineKind::Blend : (material->DoubleSided ? PipelineKind::DoubleSided : PipelineKind::Opaque);
			}
			else
			{
				if (renderer.MaterialAsset.IsValid() && impl.WarnedMissing.insert(renderer.MaterialAsset).second)
					LM_WARN("Material asset {} is not available; using the inline material", static_cast<uint64_t>(renderer.MaterialAsset));
				const MaterialData& inlineMaterial = renderer.Material;
				item.Constants.BaseColor = inlineMaterial.BaseColor;
				item.Constants.Material = glm::vec4(inlineMaterial.Metallic, inlineMaterial.Roughness, 0.0f, 0.0f);
				item.Constants.Emissive = glm::vec4(inlineMaterial.Emissive, 0.0f);
				if (inlineMaterial.BaseColor.a < 1.0f)
				{
					item.Constants.Params.w = 2.0f;
					item.Kind = PipelineKind::Blend;
				}
			}
			item.Distance = glm::length(glm::vec3(item.Constants.Model[3]) - cameraTransform.Translation);
			item.WorldBounds = item.Mesh->LocalBounds.Transformed(item.Constants.Model);
			item.CastsShadow = renderer.CastShadows && item.Kind != PipelineKind::Blend;
			draws.push_back(item);
		}

		// Opaque and masked first (any order), then blended back to front.
		std::stable_partition(draws.begin(), draws.end(), [](const DrawItem& d) { return d.Kind != PipelineKind::Blend; });
		auto firstBlend = std::find_if(draws.begin(), draws.end(), [](const DrawItem& d) { return d.Kind == PipelineKind::Blend; });
		std::stable_sort(firstBlend, draws.end(), [](const DrawItem& a, const DrawItem& b) { return a.Distance > b.Distance; });

		// --- Shadow cascade --------------------------------------------------------------------------------------------
		ShadowCascade cascade;
		bool shadowsActive = false;
		if (impl.RenderSettings.EnableShadows && hasLight)
		{
			Bounds casters;
			for (const DrawItem& item : draws)
				if (item.CastsShadow)
					casters.Expand(item.WorldBounds);
			shadowsActive = !casters.IsEmpty()
				&& ComputeDirectionalShadow(cameraWorld, cameraData.FovY, static_cast<float>(impl.Width) / static_cast<float>(impl.Height), cameraData.Near,
				                            cameraData.Far, impl.RenderSettings.ShadowDistance, glm::vec3(frame.LightDirection), casters, impl.ShadowSize, cascade);
		}
		frame.LightViewProj = cascade.ViewProj;
		frame.ShadowParams = glm::vec4(shadowsActive ? 1.0f : 0.0f, 0.0005f, 1.5f * cascade.TexelWorldSize, std::max(impl.RenderSettings.ShadowSoftness, 0.0f));
		frame.ShadowParams2 = glm::vec4(cascade.DepthRange, 2.0f * cascade.Radius, 1.0f / static_cast<float>(impl.ShadowSize), 0.0f);

		// --- Ambient occlusion parameters ------------------------------------------------------------------------------
		const float tanHalfFov = std::tan(cameraData.FovY * 0.5f);
		const float aspectRatio = static_cast<float>(impl.Width) / static_cast<float>(impl.Height);
		const bool aoActive = impl.RenderSettings.EnableAmbientOcclusion
			&& std::any_of(draws.begin(), draws.end(), [](const DrawItem& d) { return d.Kind != PipelineKind::Blend; });
		frame.ProjInfo = glm::vec4(tanHalfFov * aspectRatio, tanHalfFov, cameraData.Near, cameraData.Far);
		frame.AOParams = glm::vec4(std::max(impl.RenderSettings.AORadius, 0.01f), std::max(impl.RenderSettings.AOIntensity, 0.0f),
		                           std::max(impl.RenderSettings.AOPower, 0.01f), aoActive ? 1.0f : 0.0f);
		frame.ScreenParams = glm::vec4(static_cast<float>(impl.Width), static_cast<float>(impl.Height), 1.0f / static_cast<float>(impl.Width), 1.0f / static_cast<float>(impl.Height));

		// --- Record ----------------------------------------------------------------------------------------------------
		impl.Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
		{
			commandList->writeBuffer(impl.FrameBuffer, &frame, sizeof(frame));

			const glm::vec3& clear = impl.RenderSettings.ClearColor;
			commandList->clearTextureFloat(impl.Hdr, nvrhi::AllSubresources, nvrhi::Color(clear.r, clear.g, clear.b, 1.0f));
			commandList->clearDepthStencilTexture(impl.Depth, nvrhi::AllSubresources, true, 1.0f, false, 0);

			if (shadowsActive)
			{
				commandList->clearDepthStencilTexture(impl.ShadowMap, nvrhi::AllSubresources, true, 1.0f, false, 0);
				const nvrhi::Viewport shadowViewport(static_cast<float>(impl.ShadowSize), static_cast<float>(impl.ShadowSize));
				for (const DrawItem& item : draws)
				{
					if (!item.CastsShadow)
						continue;
					nvrhi::GraphicsState shadowState;
					shadowState.setPipeline(impl.ShadowPipeline)
						.setFramebuffer(impl.ShadowFramebuffer)
						.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(shadowViewport))
						.addBindingSet(impl.ShadowBindings);
					shadowState.vertexBuffers = { { item.Mesh->VertexBuffer, 0, 0 } };
					shadowState.indexBuffer = { item.Mesh->IndexBuffer, nvrhi::Format::R32_UINT, 0 };
					commandList->setGraphicsState(shadowState);
					const ShadowConstants constants{ item.Constants.Model, cascade.ViewProj };
					commandList->setPushConstants(&constants, sizeof(constants));
					nvrhi::DrawArguments shadowArgs;
					shadowArgs.vertexCount = item.Mesh->IndexCount;
					commandList->drawIndexed(shadowArgs);
				}
			}

			if (aoActive)
			{
				const nvrhi::Viewport screen(static_cast<float>(impl.Width), static_cast<float>(impl.Height));
				commandList->clearTextureFloat(impl.NormalTarget, nvrhi::AllSubresources, nvrhi::Color(0.0f, 0.0f, 1.0f, 0.0f));
				commandList->clearDepthStencilTexture(impl.AoDepth, nvrhi::AllSubresources, true, 1.0f, false, 0);

				for (const DrawItem& item : draws)
				{
					if (item.Kind == PipelineKind::Blend)
						continue;
					nvrhi::GraphicsState prepassState;
					prepassState.setPipeline(impl.PrepassPipelines[static_cast<size_t>(item.Kind)])
						.setFramebuffer(impl.PrepassFramebuffer)
						.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(screen))
						.addBindingSet(impl.PrepassBindings);
					prepassState.vertexBuffers = { { item.Mesh->VertexBuffer, 0, 0 } };
					prepassState.indexBuffer = { item.Mesh->IndexBuffer, nvrhi::Format::R32_UINT, 0 };
					commandList->setGraphicsState(prepassState);
					commandList->setPushConstants(&item.Constants, sizeof(item.Constants));
					nvrhi::DrawArguments prepassArgs;
					prepassArgs.vertexCount = item.Mesh->IndexCount;
					commandList->drawIndexed(prepassArgs);
				}

				auto fullscreenPass = [&](nvrhi::IGraphicsPipeline* pipeline, nvrhi::IFramebuffer* framebuffer, nvrhi::IBindingSet* bindings, const glm::vec2* pushConstants)
				{
					nvrhi::GraphicsState state;
					state.setPipeline(pipeline).setFramebuffer(framebuffer)
						.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(screen))
						.addBindingSet(bindings);
					commandList->setGraphicsState(state);
					if (pushConstants != nullptr)
						commandList->setPushConstants(pushConstants, sizeof(glm::vec2));
					nvrhi::DrawArguments args;
					args.vertexCount = 3;
					commandList->draw(args);
				};
				const glm::vec2 horizontal(1.0f / static_cast<float>(impl.Width), 0.0f);
				const glm::vec2 vertical(0.0f, 1.0f / static_cast<float>(impl.Height));
				fullscreenPass(impl.AoPipeline, impl.AoRawFramebuffer, impl.AoBindings, nullptr);
				fullscreenPass(impl.BlurHPipeline, impl.AoTempFramebuffer, impl.BlurHBindings, &horizontal);
				fullscreenPass(impl.BlurVPipeline, impl.AoFinalFramebuffer, impl.BlurVBindings, &vertical);
			}

			const nvrhi::Viewport viewport(static_cast<float>(impl.Width), static_cast<float>(impl.Height));

			if (frame.EnvParams.w > 0.5f)
			{
				nvrhi::GraphicsState skyState;
				skyState.setPipeline(impl.SkyPipeline)
					.setFramebuffer(impl.SceneFramebuffer)
					.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
					.addBindingSet(impl.SceneBindings);
				commandList->setGraphicsState(skyState);
				const DrawConstants unused{}; // the shared scene layout declares push constants; nvrhi requires them to be set
				commandList->setPushConstants(&unused, sizeof(unused));
				nvrhi::DrawArguments sky;
				sky.vertexCount = 3;
				commandList->draw(sky);
			}

			for (const DrawItem& item : draws)
			{
				nvrhi::GraphicsState state;
				state.setPipeline(impl.ScenePipelines[static_cast<size_t>(item.Kind)])
					.setFramebuffer(impl.SceneFramebuffer)
					.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
					.addBindingSet(impl.SceneBindings)
					.addBindingSet(item.Textures);
				state.vertexBuffers = { { item.Mesh->VertexBuffer, 0, 0 } };
				state.indexBuffer = { item.Mesh->IndexBuffer, nvrhi::Format::R32_UINT, 0 };
				commandList->setGraphicsState(state);
				commandList->setPushConstants(&item.Constants, sizeof(item.Constants));

				nvrhi::DrawArguments args;
				args.vertexCount = item.Mesh->IndexCount;
				commandList->drawIndexed(args);
			}

			nvrhi::GraphicsState tonemapState;
			tonemapState.setPipeline(impl.TonemapPipeline)
				.setFramebuffer(impl.OutputFramebuffer)
				.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
				.addBindingSet(impl.TonemapBindings);
			commandList->setGraphicsState(tonemapState);
			const float exposure = impl.RenderSettings.Exposure;
			commandList->setPushConstants(&exposure, sizeof(exposure));
			nvrhi::DrawArguments fullscreen;
			fullscreen.vertexCount = 3;
			commandList->draw(fullscreen);
		});
		return true;
	}

}
