#include "Lumen/Renderer/Renderer.h"

#include "Lumen/Core/Log.h"
#include "Lumen/Renderer/Mesh.h"
#include "Lumen/Scene/Scene.h"

#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>

#include <array>
#include <cstddef>

// Generated by cmake/Shaders.cmake from Lumen/shaders/.
extern const unsigned char g_Shader_mesh_vert[];
extern const size_t g_Shader_mesh_vert_size;
extern const unsigned char g_Shader_pbr_frag[];
extern const size_t g_Shader_pbr_frag_size;
extern const unsigned char g_Shader_fullscreen_vert[];
extern const size_t g_Shader_fullscreen_vert_size;
extern const unsigned char g_Shader_tonemap_frag[];
extern const size_t g_Shader_tonemap_frag_size;

namespace Lumen {

	namespace {

		// std140 layout, matches the Frame block in the shaders.
		struct FrameConstants
		{
			glm::mat4 View;
			glm::mat4 Proj;
			glm::vec4 CameraPosition;
			glm::vec4 LightDirection;
			glm::vec4 LightColor;
			glm::vec4 Ambient;
		};

		struct DrawConstants
		{
			glm::mat4 Model;
			glm::vec4 BaseColor;
			glm::vec4 Material; // x metallic, y roughness
			glm::vec4 Emissive;
		};
		static_assert(sizeof(DrawConstants) == 112, "push constants must fit the 128 byte guaranteed minimum");

		struct GpuMesh
		{
			nvrhi::BufferHandle VertexBuffer;
			nvrhi::BufferHandle IndexBuffer;
			uint32_t IndexCount = 0;
		};

		constexpr nvrhi::Format s_HdrFormat = nvrhi::Format::RGBA16_FLOAT;
		constexpr nvrhi::Format s_DepthFormat = nvrhi::Format::D32;
		constexpr nvrhi::Format s_OutputFormat = nvrhi::Format::RGBA8_UNORM;

		nvrhi::ShaderHandle CreateShader(nvrhi::IDevice* device, nvrhi::ShaderType type, const char* name, const unsigned char* data, size_t size)
		{
			return device->createShader(nvrhi::ShaderDesc().setShaderType(type).setDebugName(name), data, size);
		}

	}

	struct Renderer::Impl
	{
		Ref<RenderDevice> Device;
		Settings RenderSettings;
		uint32_t Width = 0;
		uint32_t Height = 0;

		nvrhi::TextureHandle Hdr, Depth, Output;
		nvrhi::FramebufferHandle SceneFramebuffer, OutputFramebuffer;

		nvrhi::BufferHandle FrameBuffer;
		nvrhi::SamplerHandle Sampler;

		nvrhi::BindingLayoutHandle SceneLayout, TonemapLayout;
		nvrhi::BindingSetHandle SceneBindings, TonemapBindings;
		nvrhi::InputLayoutHandle InputLayout;
		nvrhi::GraphicsPipelineHandle ScenePipeline, TonemapPipeline;

		std::array<GpuMesh, 3> Meshes; // indexed by PrimitiveType

		nvrhi::IDevice* Gpu() const { return Device->GetDevice(); }

		GpuMesh UploadMesh(const MeshData& mesh, const char* name)
		{
			LM_ASSERT(mesh.IsValid(), "invalid mesh");
			GpuMesh gpu;
			gpu.IndexCount = static_cast<uint32_t>(mesh.Indices.size());

			nvrhi::BufferDesc vertexDesc;
			vertexDesc.byteSize = mesh.Vertices.size() * sizeof(Vertex);
			vertexDesc.isVertexBuffer = true;
			vertexDesc.initialState = nvrhi::ResourceStates::VertexBuffer;
			vertexDesc.keepInitialState = true;
			vertexDesc.debugName = std::string(name) + " vertices";
			gpu.VertexBuffer = Gpu()->createBuffer(vertexDesc);

			nvrhi::BufferDesc indexDesc;
			indexDesc.byteSize = mesh.Indices.size() * sizeof(uint32_t);
			indexDesc.isIndexBuffer = true;
			indexDesc.initialState = nvrhi::ResourceStates::IndexBuffer;
			indexDesc.keepInitialState = true;
			indexDesc.debugName = std::string(name) + " indices";
			gpu.IndexBuffer = Gpu()->createBuffer(indexDesc);

			Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
			{
				commandList->writeBuffer(gpu.VertexBuffer, mesh.Vertices.data(), vertexDesc.byteSize);
				commandList->writeBuffer(gpu.IndexBuffer, mesh.Indices.data(), indexDesc.byteSize);
			});
			return gpu;
		}

		bool Initialize()
		{
			nvrhi::IDevice* gpu = Gpu();

			// --- Targets -------------------------------------------------------------------------------------------
			Hdr = Device->CreateRenderTarget(Width, Height, s_HdrFormat, "SceneHDR");
			Output = Device->CreateRenderTarget(Width, Height, s_OutputFormat, "SceneOutput");

			nvrhi::TextureDesc depthDesc;
			depthDesc.width = Width;
			depthDesc.height = Height;
			depthDesc.format = s_DepthFormat;
			depthDesc.isRenderTarget = true;
			depthDesc.initialState = nvrhi::ResourceStates::DepthWrite;
			depthDesc.keepInitialState = true;
			depthDesc.debugName = "SceneDepth";
			Depth = gpu->createTexture(depthDesc);
			if (!Hdr || !Output || !Depth)
				return false;

			SceneFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Hdr).setDepthAttachment(Depth));
			OutputFramebuffer = gpu->createFramebuffer(nvrhi::FramebufferDesc().addColorAttachment(Output));

			// --- Constant buffer and sampler -----------------------------------------------------------------------
			nvrhi::BufferDesc frameDesc;
			frameDesc.byteSize = sizeof(FrameConstants);
			frameDesc.isConstantBuffer = true;
			frameDesc.isVolatile = true;
			frameDesc.maxVersions = 8;
			frameDesc.debugName = "FrameConstants";
			FrameBuffer = gpu->createBuffer(frameDesc);

			Sampler = gpu->createSampler(nvrhi::SamplerDesc().setAllFilters(true).setAllAddressModes(nvrhi::SamplerAddressMode::Clamp));

			// --- Shaders and layouts -------------------------------------------------------------------------------
			nvrhi::ShaderHandle meshVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "mesh.vert", g_Shader_mesh_vert, g_Shader_mesh_vert_size);
			nvrhi::ShaderHandle pbrPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "pbr.frag", g_Shader_pbr_frag, g_Shader_pbr_frag_size);
			nvrhi::ShaderHandle fullscreenVs = CreateShader(gpu, nvrhi::ShaderType::Vertex, "fullscreen.vert", g_Shader_fullscreen_vert, g_Shader_fullscreen_vert_size);
			nvrhi::ShaderHandle tonemapPs = CreateShader(gpu, nvrhi::ShaderType::Pixel, "tonemap.frag", g_Shader_tonemap_frag, g_Shader_tonemap_frag_size);
			if (!meshVs || !pbrPs || !fullscreenVs || !tonemapPs)
				return false;

			std::array<nvrhi::VertexAttributeDesc, 3> attributes = {
				nvrhi::VertexAttributeDesc().setName("POSITION").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Position)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("NORMAL").setFormat(nvrhi::Format::RGB32_FLOAT).setOffset(offsetof(Vertex, Normal)).setElementStride(sizeof(Vertex)),
				nvrhi::VertexAttributeDesc().setName("TEXCOORD").setFormat(nvrhi::Format::RG32_FLOAT).setOffset(offsetof(Vertex, UV)).setElementStride(sizeof(Vertex)),
			};
			InputLayout = gpu->createInputLayout(attributes.data(), static_cast<uint32_t>(attributes.size()), meshVs);

			SceneLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::VolatileConstantBuffer(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(DrawConstants))));
			SceneBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::ConstantBuffer(0, FrameBuffer))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(DrawConstants))), SceneLayout);

			TonemapLayout = gpu->createBindingLayout(nvrhi::BindingLayoutDesc()
				.setVisibility(nvrhi::ShaderType::All)
				.addItem(nvrhi::BindingLayoutItem::Texture_SRV(0))
				.addItem(nvrhi::BindingLayoutItem::Sampler(0))
				.addItem(nvrhi::BindingLayoutItem::PushConstants(1, sizeof(float))));
			TonemapBindings = gpu->createBindingSet(nvrhi::BindingSetDesc()
				.addItem(nvrhi::BindingSetItem::Texture_SRV(0, Hdr))
				.addItem(nvrhi::BindingSetItem::Sampler(0, Sampler))
				.addItem(nvrhi::BindingSetItem::PushConstants(1, sizeof(float))), TonemapLayout);

			// --- Pipelines -----------------------------------------------------------------------------------------
			nvrhi::GraphicsPipelineDesc sceneDesc;
			sceneDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setInputLayout(InputLayout)
				.setVertexShader(meshVs)
				.setPixelShader(pbrPs)
				.addBindingLayout(SceneLayout);
			sceneDesc.renderState.depthStencilState.depthTestEnable = true;
			sceneDesc.renderState.depthStencilState.depthWriteEnable = true;
			sceneDesc.renderState.depthStencilState.depthFunc = nvrhi::ComparisonFunc::Less;
			sceneDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::Back;
			// The projection flips Y for Vulkan, which makes counter-clockwise (world) triangles clockwise in framebuffer space.
			sceneDesc.renderState.rasterState.frontCounterClockwise = false;
			ScenePipeline = gpu->createGraphicsPipeline(sceneDesc, SceneFramebuffer->getFramebufferInfo());

			nvrhi::GraphicsPipelineDesc tonemapDesc;
			tonemapDesc.setPrimType(nvrhi::PrimitiveType::TriangleList)
				.setVertexShader(fullscreenVs)
				.setPixelShader(tonemapPs)
				.addBindingLayout(TonemapLayout);
			tonemapDesc.renderState.depthStencilState.depthTestEnable = false;
			tonemapDesc.renderState.depthStencilState.depthWriteEnable = false;
			tonemapDesc.renderState.rasterState.cullMode = nvrhi::RasterCullMode::None;
			TonemapPipeline = gpu->createGraphicsPipeline(tonemapDesc, OutputFramebuffer->getFramebufferInfo());
			if (!ScenePipeline || !TonemapPipeline)
				return false;

			Meshes[static_cast<size_t>(PrimitiveType::Cube)] = UploadMesh(MeshGenerator::CreateCube(), "Cube");
			Meshes[static_cast<size_t>(PrimitiveType::Sphere)] = UploadMesh(MeshGenerator::CreateSphere(48, 24), "Sphere");
			Meshes[static_cast<size_t>(PrimitiveType::Plane)] = UploadMesh(MeshGenerator::CreatePlane(), "Plane");
			return true;
		}
	};

	Ref<Renderer> Renderer::Create(Ref<RenderDevice> device, uint32_t width, uint32_t height)
	{
		if (!device || width == 0 || height == 0)
		{
			LM_ERROR("Renderer needs a device and a non-zero size");
			return nullptr;
		}

		Ref<Renderer> renderer(new Renderer());
		renderer->m_Impl = CreateScope<Impl>();
		renderer->m_Impl->Device = std::move(device);
		renderer->m_Impl->Width = width;
		renderer->m_Impl->Height = height;
		if (!renderer->m_Impl->Initialize())
		{
			LM_ERROR("Failed to create renderer GPU resources");
			return nullptr;
		}
		return renderer;
	}

	Renderer::~Renderer()
	{
		if (m_Impl && m_Impl->Device)
			m_Impl->Device->GetDevice()->waitForIdle();
	}

	Renderer::Settings& Renderer::GetSettings() { return m_Impl->RenderSettings; }
	uint32_t Renderer::GetWidth() const { return m_Impl->Width; }
	uint32_t Renderer::GetHeight() const { return m_Impl->Height; }
	nvrhi::ITexture* Renderer::GetOutput() const { return m_Impl->Output; }
	nvrhi::ITexture* Renderer::GetHdrTarget() const { return m_Impl->Hdr; }
	ImageData Renderer::ReadOutput() { return m_Impl->Device->ReadTexture(m_Impl->Output); }

	bool Renderer::Render(Scene& scene, Entity camera)
	{
		if (!camera.IsValid() || !camera.HasComponent<CameraComponent>())
		{
			LM_ERROR("Renderer::Render needs a valid camera entity with a CameraComponent");
			return false;
		}

		Impl& impl = *m_Impl;
		entt::registry& registry = scene.GetRegistry();

		// --- Camera ----------------------------------------------------------------------------------------------------
		const CameraComponent& cameraData = camera.GetComponent<CameraComponent>();
		const TransformComponent& cameraTransform = camera.GetComponent<TransformComponent>();
		const glm::mat4 cameraWorld = glm::translate(glm::mat4(1.0f), cameraTransform.Translation) * glm::mat4_cast(glm::quat(cameraTransform.Rotation));

		FrameConstants frame{};
		frame.View = glm::inverse(cameraWorld);
		frame.Proj = glm::perspectiveRH_ZO(cameraData.FovY, static_cast<float>(impl.Width) / static_cast<float>(impl.Height), cameraData.Near, cameraData.Far);
		frame.Proj[1][1] *= -1.0f; // Vulkan clip space has Y pointing down
		frame.CameraPosition = glm::vec4(cameraTransform.Translation, 1.0f);
		frame.Ambient = glm::vec4(impl.RenderSettings.Ambient, 0.0f);

		// --- Light -----------------------------------------------------------------------------------------------------
		frame.LightDirection = glm::vec4(0.0f, -1.0f, 0.0f, 0.0f);
		frame.LightColor = glm::vec4(0.0f);
		for (auto [handle, transform, light] : registry.view<TransformComponent, DirectionalLightComponent>().each())
		{
			const glm::vec3 direction = glm::quat(transform.Rotation) * glm::vec3(0.0f, 0.0f, -1.0f);
			frame.LightDirection = glm::vec4(direction, 0.0f);
			frame.LightColor = glm::vec4(light.Color, light.Intensity);
			break; // a single directional light for now
		}

		// --- Record ----------------------------------------------------------------------------------------------------
		impl.Device->ExecuteImmediate([&](nvrhi::ICommandList* commandList)
		{
			commandList->writeBuffer(impl.FrameBuffer, &frame, sizeof(frame));

			const glm::vec3& clear = impl.RenderSettings.ClearColor;
			commandList->clearTextureFloat(impl.Hdr, nvrhi::AllSubresources, nvrhi::Color(clear.r, clear.g, clear.b, 1.0f));
			commandList->clearDepthStencilTexture(impl.Depth, nvrhi::AllSubresources, true, 1.0f, false, 0);

			const nvrhi::Viewport viewport(static_cast<float>(impl.Width), static_cast<float>(impl.Height));
			nvrhi::GraphicsState state;
			state.setPipeline(impl.ScenePipeline)
				.setFramebuffer(impl.SceneFramebuffer)
				.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
				.addBindingSet(impl.SceneBindings);

			for (auto [handle, transform, mesh] : registry.view<TransformComponent, MeshRendererComponent>().each())
			{
				const GpuMesh& gpuMesh = impl.Meshes[static_cast<size_t>(mesh.Primitive)];
				state.vertexBuffers = { { gpuMesh.VertexBuffer, 0, 0 } };
				state.indexBuffer = { gpuMesh.IndexBuffer, nvrhi::Format::R32_UINT, 0 };
				commandList->setGraphicsState(state);

				DrawConstants draw;
				draw.Model = transform.GetTransform();
				draw.BaseColor = mesh.Material.BaseColor;
				draw.Material = glm::vec4(mesh.Material.Metallic, mesh.Material.Roughness, 0.0f, 0.0f);
				draw.Emissive = glm::vec4(mesh.Material.Emissive, 0.0f);
				commandList->setPushConstants(&draw, sizeof(draw));

				nvrhi::DrawArguments args;
				args.vertexCount = gpuMesh.IndexCount;
				commandList->drawIndexed(args);
			}

			nvrhi::GraphicsState tonemapState;
			tonemapState.setPipeline(impl.TonemapPipeline)
				.setFramebuffer(impl.OutputFramebuffer)
				.setViewport(nvrhi::ViewportState().addViewportAndScissorRect(viewport))
				.addBindingSet(impl.TonemapBindings);
			commandList->setGraphicsState(tonemapState);
			const float exposure = impl.RenderSettings.Exposure;
			commandList->setPushConstants(&exposure, sizeof(exposure));
			nvrhi::DrawArguments fullscreen;
			fullscreen.vertexCount = 3;
			commandList->draw(fullscreen);
		});
		return true;
	}

}
