# Usage: cmake -DINPUT=<file> -DOUTPUT=<cpp> -DSYMBOL=<name> -P EmbedBinary.cmake
# Converts a binary file into a C++ source defining `extern const unsigned char SYMBOL[]` and `SYMBOL_size`.
file(READ ${INPUT} CONTENT HEX)
string(LENGTH "${CONTENT}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${CONTENT}")
file(WRITE ${OUTPUT} "// Generated by EmbedBinary.cmake - do not edit.\n#include <cstddef>\nextern const unsigned char ${SYMBOL}[];\nextern const size_t ${SYMBOL}_size;\nconst unsigned char ${SYMBOL}[] = { ${BYTES} };\nconst size_t ${SYMBOL}_size = ${BYTE_COUNT};\n")
